spring:
  application:
    name: Navalis
  mvc:
    problemdetails:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${CHAVE_POSTGRES_PORT}/${CHAVE_POSTGRES_DB}
    username: ${CHAVE_POSTGRES_USER}
    password: ${CHAVE_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  web:
    error:
      include-stacktrace: never

server:
  port: 5000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:navalis-default-secret-key-that-should-be-changed-in-production}
